config/routes.rb
Rails.application.routes.draw do
  root "boot#index"
  resources :airplanes, except: [:show, :edit, :update] 
end

app/models/airplane.rb
class Airplane < ApplicationRecord
  validates :priority, presence: true
  validates :size, presence: true
  validates :cargo_type, presence: true

  def self.enqueue(params)
    plane = Airplane.new(params)
    #we have to assign a placeholder priority so the validity check works
    plane.priority = 0 
    return plane unless plane.valid?
    plane.priority = calculate_priority(params)
    plane.save
    plane
  end

  def self.calculate_priority(params)
    #the lower the number the sooner the plane is dequeued. 
    priority = 1
    priority += 2 if params["cargo_type"] == "cargo"
    priority += 1 if params["size"] == "small"
    priority
  end

  def self.dequeue
    return false if Airplane.all.empty?
    #this says grab the plane with the highest priority that was updated last chronologically
    plane = Airplane.order(:priority, :updated_at).first
    plane.destroy
  end
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  def index
    @airplanes = Airplane.all.order(:priority, :updated_at)
  end

  def new
  end

  def create
    @airplane = Airplane.enqueue(airplane_params)
    if @airplane.valid?
      flash[:success] = "Plane added to queue"
    else
      flash[:danger] = @airplane.errors.full_messages.first 
    end
    redirect_to action: "new"
  end

  def destroy
    @airplane = Airplane.dequeue
    if @airplane
      flash[:success] = "Airplane #{@airplane[:name]}, with id #{@airplane[:id]} was successfuly Dequeued"
    else
      flash[:danger] = "there were no planes to dequeue"
    end
    redirect_to action: "new"
  end


  def airplane_params 
    params.require(:airplane).permit(:name, :size, :cargo_type)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boot_controller.rb
class BootController < ApplicationController

  def index
  end
  
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boot_helper.rb
module BootHelper
end

app/views/airplanes/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1> Welcome to the Plane Queue</h1>
  </div> 
  <div class="col-md-12">
    <p> This is the order planes will dequeue in </p>
  </div>
</div>

<div class="row">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Plane Name</th>
        <th>ID</th>
        <th>Cargo Type</th>
        <th>Size</th>
        <th>Priority</th>
        <th>Minutes In Air</th>
      </tr>
    </thead>
    <tbody>
      <% @airplanes.each do |airplane|%>
      <tr>
        <td><%=airplane.name%></td>
        <td><%=airplane.id%></td>
        <td><%=airplane.cargo_type%></td>
        <td><%=airplane.size%></td>
        <td><%=airplane.priority%></td>
        <td><%=((Time.now - airplane.created_at)/60).to_i%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="form-group row">
  <div class="col-sm-10">
    <%= button_to "Back To Control", new_airplane_path, {method: :get, class: "btn btn-primary"} %>
  </div>
</div>

app/views/airplanes/new.html.erb
<br>
<div class="row">
  <div class="col-sm-6 col-sm-offset-4">
    <h2>Aircraft Control Center</h2>
  </div>
</div>

<%= form_for Airplane.new do |f| %>
  <div class="form-group row">
    <label class="col-sm-1 col-form-label" for="name">Name:</label>
    <div class="col-sm-11">
      <%= f.text_field :name, {class: "form-control", id: "name"} %>
    </div>
  </div>  
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Size:</label>
    <div class="col-sm-10">
      <%= f.select :size, ["large", "small"],{include_blank: true}, {class: "form-control"} %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Cargo Type:</label>
    <div class="col-sm-10">
      <%= f.select :cargo_type, ["passenger", "cargo"], {include_blank: true}, {class: "form-control"}%>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-10">
      <%= f.submit "Queue Plane", class: "btn btn-primary btn-lg" %>
    </div>

<% end %>
    <div class="col-sm-2">
      <%= button_to "Dequeue Plane", airplane_path(5), {method: :delete, class: "btn btn-danger btn-lg"} %>
    </div>
  </div>

<div class="form-group row">
  <div class="col-sm-10">
    <%= button_to "View Queue", airplanes_path, {method: :get, class: "btn btn-primary"} %>
  </div>
</div>

app/views/boot/index.html.erb
<div class="row">
  <div class="col-xs-6 col-md-offset-2">
  <h3> Welcome to the ACS Operations Center </h3>
  </div>
</div>

<br>
<br>
<br>

<div class="row">
  <div class="col-xs-6 col-md-offset-3">
    <%= button_to "Initiate Airplane Control System",  new_airplane_path, {method: "get", class: "btn btn-primary btn-lg"} %>
      
  <div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airplanes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>  
    <%= yield %>
  </body>
</html>